version: '3.8'

services:
  vpn_bot:
    build: .
    container_name: marzban_bot
    restart: always
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - ./db_data:/app/database_folder
      - ./logs:/app/logs